name: 🐛 Bug Report
description: Report an error, typo, or incorrect information in the repository
title: "[BUG] Brief description of the issue"
labels: ["bug", "needs-verification"]
body:
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Broken link
        - Incorrect information
        - Typo/spelling error
        - Formatting issue
        - Missing information
        - Wrong category
        - Duplicate entry
        - Other
    validations:
      required: true
  
  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the bug located?
      placeholder: ex. Ubuntu section, Arch Linux description, etc.
    validations:
      required: true
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug in detail
      placeholder: Clearly describe what's wrong
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Information
      description: What should the correct information be?
      placeholder: Provide the correct information or expected behavior
  
  - type: input
    id: source-reference
    attributes:
      label: Source/Reference
      description: Provide a source for the correct information
      placeholder: Official documentation, website, etc.
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context about the bug
      placeholder: Screenshots, links, or other relevant information
